spring:
  config:
    activate:
      on-profile: local

  docker:
    compose:
      enabled: true

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true