server:
  port: 8080

spring:
  profiles:
    include: datasource
    group:
      default: default
      dev: dev
      local: local, sql-init

  devtools:
    livereload:
      enabled: false

  docker:
    compose:
      enabled: false

  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info
    org.hibernate.SQL: info