spring:
  config:
    activate:
      on-profile: datasource

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${mariadb-host}:${mariadb-port}/${mariadb-schema}
    username: ${mariadb-user}
    password: ${mariadb-password}
    hikari:
      maximum-pool-size: 10
      max-lifetime: 28500000 #DB WAIT_TIMEOUT -> 28800 (28800000)